function results2csv(rfile,ofile,lines,mode)
%
% function results2csv(rfile,ofile,lines,mode)
%
%   rfile    :
%       name of the file with the results.
%   ofile    :
%        name of the output file.
%   lines    :
%        determines the lines of the results variables
%        in the rfile that will be considered.
%   mode     :
%       define the columns that will be considered.
%
%       'hd'
%       |EbNo|Time[s]|nWords|nErrors|WER|nBits|nEBit|BER|BERCh|
%
%       'sd'
%       |EbNo|Time[s]|nWords|HD|SD|nErrors|WER|nBits|nEBit|BER|BERCh|
%
%       'cand_bits'
%       |EbNo|avgCand|avgNDiffBits|-e N|-gte N3/4|-gte N/2|-gte N/3|
%
%       'time'          =>
%       |EbNo|Time|
%

load(rfile);

if(mode=="hd")
    t = table(...
        results(lines,1),...
        results(lines,3),...
        results(lines,7),...
        results(lines,10),...
        results(lines,12),...
        'VariableNames',...
        header(1,[1 3 7 10 12])...
        );
    writetable(t,ofile);
elseif(mode=="hdE")
    t = table(...
        results(lines,1),...
        results(lines,3),...
        results(lines,7),...
        results(lines,9),...
        results(lines,10),...
        results(lines,12),...
        'VariableNames',...
        header(1,[1 3 7 9 10 12])...
        );
    writetable(t,ofile);
elseif(mode=="sd")
    t = table(...        
        results(lines,1),...
        results(lines,3),...
        results(lines,5),...
        results(lines,7),...
        results(lines,8),...
        results(lines,10),...
        results(lines,12),...
        'VariableNames',...
        header(1,[1 3 5 7 8 10 12])...
        );
    writetable(t,ofile);
elseif(mode=="sdE")
    t = table(...        
        results(lines,1),...
        results(lines,3),...
        results(lines,5),...
        results(lines,7),...
        results(lines,8),...
        results(lines,9),...
        results(lines,10),...
        results(lines,12),...
        'VariableNames',...
        header(1,[1 3 5 7 8 9 10 12])...
        );
    writetable(t,ofile);
elseif(mode=="cand_bits")
    t = table(...        
        results(lines,1),...
        results(lines,13),...
        results(lines,14),...
        results(lines,15),...
        results(lines,16),...
        results(lines,17),...
        results(lines,18),...
        'VariableNames',...
        header(1,[1 13 14 15 16 17 18])...
        );
    writetable(t,ofile);
elseif(mode=="time")
    t = table(...        
        results(lines,1),...
        results(lines,2),...
        'VariableNames',...
        header(1,[1 2])...
        );
    writetable(t,ofile);
end